### ISSUE TITLE
After enter setting and back, the upper region become blank. Only in android 8.1.0.

### ISSUE THREAD

**Issue by gemscng** [measurabledatatoken/mymdt#34]
Device: Red Mi 6
OS: android 8.1.0

![IMG_6233](https://user-images.githubusercontent.com/7820794/66187873-6129a180-e6b8-11e9-9e2e-e21d555e288e.jpg)

**Comment by chochihim** [comment]
This issue is related to the use of Vue's `transition` on `router-view`. Looks like Redmi webview engine has quirky behaviour with it.
