### ISSUE TITLE
PIN popup will still show when clicking the Edit ETH wallet button

### ISSUE THREAD

**Issue by mattlung** [measurabledatatoken/mymdt#54]
I have two emails
1) has PIN setup
2) no PIN

Procedures to reproduce
1) clicks account 2 in home page
2) clicks 數據獎勵 button
3) it will show the selected user is account 1 on current page
4) clicks Edit ETH button, PIN setup popup will be shown.

**Comment by gemscng** [comment]
@mattlung  Please help verify

**Comment by mattlung** [comment]
confirm fixed
